### ISSUE TITLE
Take a look at journey docs as guide

### ISSUE THREAD

**Issue by rhagarty** [RiyaMRoy04/CalorieCounterApp#1]
Hello Riya - I'll be working with you on this journey. 

Journey idea looks great, we just need to get the documentation and support added.

Please take a look at https://github.ibm.com/developer-journeys/journey-docs to help guide you through this process. 

Let's communicate on Slack.

**Comment by RiyaMRoy04** [comment]
I have added the documentation and updated the README.md. Please check here: https://github.com/RiyaMRoy04/CalorieCounterApp
