### ISSUE TITLE
Error building cordova android version

### ISSUE THREAD

**Issue by rhagarty** [RiyaMRoy04/CalorieCounterApp#2]
rhagarty@Richs-MBP-15 mobile (master) $ cordova platform version android
Installed platforms:
  android 6.2.3
Available platforms:
  blackberry10 ~3.8.0 (deprecated)
  browser ~4.1.0
  ios ~4.4.0
  osx ~4.0.1
  webos ~3.7.0
rhagarty@Richs-MBP-15 mobile (master) $ cordova build android --verbose
No scripts found for hook "before_build".
No scripts found for hook "before_prepare".
Checking config.xml and package.json for saved platforms that haven't been added to the project
Config.xml and package.json platforms are the same. No pkg.json modification.
Package.json and config.xml platforms are different. Updating config.xml with most current list of platforms.
 Using this version of Cordova with older version of cordova-android is deprecated. Upgrade to cordova-android@5.0.0 or newer.
Error: Your android platform does not have Api.js

**Comment by RiyaMRoy04** [comment]
Which version of cordova are you using?
This may be because of Cordova/Node.js version issue. Can you try upgrading cordova or Node.js version?

**Comment by rhagarty** [comment]
I upgraded to v7.0.0

rhagarty@Richs-MBP-15 mobile (master) $ cordova -v
7.0.0

**Comment by RiyaMRoy04** [comment]
@rhagarty I have updated the mobile code by removing android platform and other plugins. Can you check by cloning the code again?

**Comment by RiyaMRoy04** [comment]
Hi @rhagarty Were you able to build the app?

**Comment by rhagarty** [comment]
Got it to build. Thanks
