### ISSUE TITLE
README instructions wrong?

### ISSUE THREAD

**Issue by rhagarty** [RiyaMRoy04/CalorieCounterApp#3]
Got errors running these commands:
  cordova plugin add org.apache.cordova.camera
  cordova plugin add org.apache.cordova.file-transfer

But it worked with these commands:
  cordova plugin add cordova-plugin-camera
  cordova plugin add cordova-plugin-file-transfer

**Comment by RiyaMRoy04** [comment]
Yes, I have updated the README with the correct commands
