### ISSUE TITLE
README architecture diagram and flow section

### ISSUE THREAD

**Issue by rhagarty** [RiyaMRoy04/CalorieCounterApp#4]
Remove step 1 from the "Flow" steps. The flow should represent application flow, not installation steps.

It should be something like:
1. User interacts with the mobile app and captures an image.
2. The image is passed to the server application which uses Watson Visual Recognition Service to analyze the images and Nutritionix API to provide nutritional information. 
3. Data is returned to the mobile app for display.

The architecture diagram should have 3 sections - User, Cloud, and External.

User - User and mobile app
Cloud - Server application and Watson VR
External - Nutritionix

**Comment by RiyaMRoy04** [comment]
@rhagarty I have updated the Flow and architecture diagram.

**Comment by rhagarty** [comment]
Look good
