### ISSUE TITLE
Put app keys in .env file

### ISSUE THREAD

**Issue by rhagarty** [RiyaMRoy04/CalorieCounterApp#5]
We shouldn't have the user update source to set the key vales. Instead, create an env.sample file with something like:
NUTRITIONIX_APP_ID=<add_app_id>
NUTRITIONIX_APP_KEY=<add_app_key>

Then add to instructions that user must:
cp env.sample .env
and update the values
(see https://github.com/IBM/watson-multimedia-analyzer for example of this step)

Then have mobile/www/js/index.js read from the .env file to get these values.
Also, add .env to .gitignore

**Comment by stevemart** [comment]
alternatively, we could have the user input the id and key with a simple text box when the app first loads, and write the values to memory as application data

**Comment by RiyaMRoy04** [comment]
Thanks @rhagarty and @stevemart for suggestions. Since mobile app is developed in Cordova, I have included credentials inside config.json and is parsing that to get the key values so that user doesn't have to change source code and only update config.json . I have updated the README likewise.
