### ISSUE TITLE
Need more info on apiURL

### ISSUE THREAD

**Issue by rhagarty** [RiyaMRoy04/CalorieCounterApp#6]
What is the new field apiURL var used for? (in index.js)

Need to add this to the readme instructions. (what it's for and where to get the URL)

**Comment by RiyaMRoy04** [comment]
Hi @rhagarty API URL is SERVER URL for the server to receive the image file for analyzing image using Visual Recognition, as encoded by encodeURI(). To get that URL,we have to first deploy the application to IBM Bluemix. Have updated it in the README as well..
