### ISSUE TITLE
Cordova requirements check fails

### ISSUE THREAD

**Issue by rhagarty** [RiyaMRoy04/CalorieCounterApp#7]
Looks like I need to manually set some env variables. I think we should add this to the README instructions. Here is the error:

$ cordova requirements

Requirements check results for android:
Java JDK: installed 1.8.0
Android SDK: not installed
Failed to find 'ANDROID_HOME' environment variable. Try setting setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
Android target: not installed
android: Command failed with exit code ENOENT
Gradle: not installed
Could not find gradle wrapper within Android SDK. Could not find Android SDK directory.
Might need to install Android SDK or set up 'ANDROID_HOME' env variable.
Error: Some of requirements check failed

┌──────────────────────────────────────────┐
│ Update available: 7.0.1 (current: 7.0.0) │
│ Run npm install -g cordova to update.    │
└──────────────────────────────────────────┘

**Comment by RiyaMRoy04** [comment]
Hi @rhagarty I had added a line in README.MD (just after adding the platform) (Check if you satisfy requirements for building the platform [here](https://cordova.apache.org/docs/en/latest/guide/cli/#install-pre-requisites-for-building)) . However, I have added that line in the Pre-requisites section as well.
